/**
 * Embedded Ed25519 PUBLIC key for license verification.
 *
 * ⚠️  AUTO-GENERATED by `npm run license:keygen`. Do not edit by hand.
 *
 * This is the public half of the key pair — it can ONLY verify signatures, not
 * create them, so it is safe to ship inside the POS. The matching PRIVATE key
 * lives exclusively on the license server (gitignored / env secret) and must
 * never be distributed.
 */
export const PUBLIC_KEY_PEM = `-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEA2dm0VFmJ8t1D3FKrejXY89kZJgL86sNiDNxi5NGKRyU=
-----END PUBLIC KEY-----`;
